### ISSUE TITLE
install fails on serial dependency

### ISSUE THREAD

**Issue by hex705** [colinbdclark/osc.js-examples#8]
HI  ---

tried to global install OSC via npm on rPi.
rPI 3.0
Node version v6.10.2

Get this  error:
pi@raspberrypi:~ $ sudo npm install osc -g

> serialport@4.0.7 install /usr/local/lib/node_modules/osc/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v48-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@6.10.2 (node-v48 ABI) (falling back to source compile with node-gyp) 

The ARM version of serial for this release (4.0.7)  does not exist.

thots?

steve

**Comment by colinbdclark** [comment]
Hi @hex705, sorry to hear you're having trouble. 

Unfortunately I don't have a Raspberry Pi on hand at the moment, so I can't test it myself. Based on the snippet of the message you're receiving, it looks to me like the error isn't fatal—if node-pre-gyp doesn't find a pre-built binary, it will compile it. 

In your case, does the compilation fail? If so, what does the rest of the error message say? Have you followed all the [instructions for compiling node-serialport on Raspberry Pi](https://github.com/EmergingTechnologyAdvisors/node-serialport#raspberry-pi-linux) in their documentation?

When I find time, I am planning to modularize osc.js' transports so the core will not depend directly on node-serialport for those users who aren't using OSC over serial, but for now unfortunately it is a direct dependency of the project.

**Comment by hex705** [comment]
hey thanks for getting back to me...

I rolled back to node version 4.X.X and it is happier.

will do more testing and gat you more info.

I think it has now installed .... OSC would not install globally (-g)  ....
but it seems to have installed (at least it says it did ... have not got
that far in testing) if I install to a local project.  (---save, into
project modules folder)

not sure why that is the case

will keep working on it and see what happens and get back to you.

steve



--
Steve Daniels
Director, New Media Program
RTA School of Media
Ryerson University
Toronto, ON, Canada

www.spinningtheweb.org

twitter (program)  @RyersonNewMedia

**Comment by hex705** [comment]
hi colin,

not sure if this actually gets to you and I can;t recall where I stuck my
first message on your git hub repo.

anyway, with node 4.x.x i can can get osc to run in node in osx and talk to
processing (processing.org).

which is awesome ....  next step is talking to an arduino directly.

also, I see you are down the street at ocad.  that's pretty funny ... I am
at ryerson.

great lib so far, thanks.  will keep you posted as I get back to my pi and
doing tests in that context.

s




--
Steve Daniels
Director, New Media Program
RTA School of Media
Ryerson University
Toronto, ON, Canada

www.spinningtheweb.org

twitter (program)  @RyersonNewMedia

**Comment by colinbdclark** [comment]
I'm closing this issue since it sounds like it was resolved years ago. :)
